---
version: "2.1"
services:
  sonarr:
    image: linuxserver/sonarr:preview
    container_name: sonarr
    network_mode: host
    environment:
      - PUID=112
      - GUID=117
    volumes:
      - /media:/media
      - /root/docker/sonarr_radarr/sonarr/config:/config
    restart: unless-stopped
  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    network_mode: host
    environment:
      - PUID=112
      - GUID=117
    volumes:
      - /media:/media
      - /root/docker/sonarr_radarr/radarr/config:/config
    restart: unless-stopped
